- hosts: access_1_sw
  roles:
    - role: arubanetworks.aoscx_role
  gather_facts: false

  vars:
    ansible_connection: httpapi

  tasks:
    - name: Create VLAN 300 - Students
      aoscx_vlan:
        vlan_id: 300
        name: STUDENTS_VLAN

